options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/isyara-repo/isyara-all:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/isyara-repo/isyara-all:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/isyara-repo/isyara-all:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/isyara-repo/isyara-all:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'isyara-all'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/isyara-repo/isyara-all:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/isyara-repo/isyara-all:$COMMIT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/isyara-repo/isyara-all:latest'
