# Generated by Django 5.2.17 on 2026-08-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lesson_ai_practice_available_lesson_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_hands', models.JSONField(blank=True, default=list)),
                ('active_hand', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], default='right', max_length=12)),
                ('uses_face', models.BooleanField(default=False)),
                ('uses_upper_body', models.BooleanField(default=True)),
                ('is_dynamic', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, default='BISINDO', max_length=120)),
                ('reference_video_path', models.CharField(blank=True, max_length=255)),
                ('reference_landmarks_path', models.CharField(blank=True, max_length=255)),
                ('component_weights', models.JSONField(blank=True, default=dict)),
                ('reference_features', models.JSONField(blank=True, default=dict)),
                ('manually_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reference', to='learning.lesson')),
            ],
            options={
                'ordering': ['lesson__order'],
            },
        ),
    ]
