# Generated by Django 5.2.17 on 2026-08-09 14:27

import apps.learning.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_aireference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to=apps.learning.models.profile_photo_upload_path, validators=[apps.learning.models.validate_profile_photo])),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('learning_level', models.CharField(choices=[('pemula', 'Pemula'), ('menengah', 'Menengah'), ('lanjutan', 'Lanjutan')], default='pemula', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
