from django.urls import path

from . import views

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="landing"),
    path("accounts/signup/", views.SignupView.as_view(), name="signup"),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout"),
    path("accounts/password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("translate/", views.TranslatorView.as_view(), name="translator"),
    path("history/", views.HistoryView.as_view(), name="translation_history"),
    path("history/<int:history_id>/delete/", views.DeleteHistoryItemView.as_view(), name="delete_translation_history"),
    path("history/clear/", views.ClearHistoryView.as_view(), name="clear_translation_history"),
    path("onboarding/", views.OnboardingView.as_view(), name="onboarding"),
    path("learn/", views.LearningPathView.as_view(), name="learning_path"),
    path("profil/", views.ProfileView.as_view(), name="profile"),
    path("profil/edit/", views.ProfileEditView.as_view(), name="profile_edit"),
    path("library/", views.LearningLibraryView.as_view(), name="library"),
    path("lessons/<slug:slug>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path("lessons/<slug:slug>/practice/", views.StartPracticeView.as_view(), name="start_practice"),
    path("practice/<int:session_id>/camera/", views.AIPracticeView.as_view(), name="practice_camera"),
    path("practice/<int:session_id>/analyze/", views.AnalyzePracticeView.as_view(), name="analyze_practice"),
    path("practice/<int:session_id>/result/", views.PracticeResultView.as_view(), name="practice_result"),
    path("dashboard/", views.ProgressDashboardView.as_view(), name="dashboard"),
    path("api/me/", views.MeAPIView.as_view(), name="api_me"),
    path("api/learning-path/", views.LearningPathAPIView.as_view(), name="api_learning_path"),
    path("api/modules/<int:module_id>/", views.ModuleDetailAPIView.as_view(), name="api_module_detail"),
    path("api/lessons/<slug:slug>/", views.LessonDetailAPIView.as_view(), name="api_lesson_detail"),
    path("api/lessons/<slug:slug>/start/", views.StartLessonAPIView.as_view(), name="api_lesson_start"),
    path("api/progress/", views.ProgressAPIView.as_view(), name="api_progress"),
    path("api/translator/predict-sign/", views.PredictSignAPIView.as_view(), name="api_predict_sign"),
    path("api/translator/transcribe/", views.TranscribeSpeechAPIView.as_view(), name="api_transcribe_speech"),
    path("api/translator/history/", views.SaveTranslationHistoryAPIView.as_view(), name="api_save_translation_history"),
    path("api/chatbot/", views.chatbot_reply_view, name="chatbot_reply"),
]
